name: Build Flutter Web and Deploy to Netlify

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allow manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'
          channel: 'stable'
          cache: true
      
      - name: Create secrets file
        run: |
          mkdir -p lib
          cat > lib/secrets.dart << EOF
          const String kGroqApiKey = '${{ secrets.KGROQ_API_KEY }}';
          const String kSupabaseUrl = '${{ secrets.KSUPABASE_URL }}';
          const String kSupabaseAnonKey = '${{ secrets.KSUPABASE_ANON_KEY }}';
          EOF
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Build web
        run: flutter build web --release
      
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './build/web'
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

